spring:

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml